### ISSUE TITLE
a mistake in from genome_tools.plotting import pwm

### ISSUE THREAD

**Issue by shangguandong1996** [jvierstra/genome-tools#3]
Hi, I am trying to use the script in https://github.com/jvierstra/motif-clustering/blob/master/viz_cluster.py

But I there is a error 

```
$ python2 viz_cluster.py tomtom/height.0.70/cluster-info.62.txt tomtom/height.0.70/cluster-motifs.62.txt tomtom/height.0.70/viz/cluster.62
Traceback (most recent call last):
  File "viz_cluster.py", line 21, in <module>
    from genome_tools.plotting import pwm
  File "/home/sgd/.local/lib/python2.7/site-packages/genome_tools-1.0.3-py2.7.egg/genome_tools/__init__.py", line 3, in <module>
    from .genomic_interval import *
  File "/home/sgd/.local/lib/python2.7/site-packages/genome_tools-1.0.3-py2.7.egg/genome_tools/genomic_interval.py", line 32
    return f"{self.chrom}:{self.start}-{self.end}"
                                                 ^
SyntaxError: invalid syntax
(intervene_module) 

```

If I just use python2 and type this line, there is still a error

```
$ python2
Python 2.7.17 |Anaconda, Inc.| (default, Oct 21 2019, 19:04:46) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from genome_tools.plotting import pwm
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sgd/.local/lib/python2.7/site-packages/genome_tools-1.0.3-py2.7.egg/genome_tools/__init__.py", line 3, in <module>
    from .genomic_interval import *
  File "/home/sgd/.local/lib/python2.7/site-packages/genome_tools-1.0.3-py2.7.egg/genome_tools/genomic_interval.py", line 32
    return f"{self.chrom}:{self.start}-{self.end}"
                                                 ^
SyntaxError: invalid syntax

```

Best wishes

Guandong Shang

**Comment by shangguandong1996** [comment]
sorry, it may because of my install mistake.
